1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
print(np.random.rand(3,3))

[[0.66022844 0.17046783 0.79398627]
 [0.42662366 0.67138109 0.91129733]
 [0.60255276 0.58422189 0.78304543]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [3]:
#please provide your answer below this line.
import numpy as np
a=np.random.rand(4,4)
b=np.random.rand(4,4)
c=np.reshape(a,(2,8))
d=np.reshape(b,(2,8))
print(np.vstack((c,d)))
print()
print(np.hstack((c,d)))

[[0.88296699 0.65133213 0.74443187 0.05316849 0.31516231 0.56292544
  0.59476785 0.18868536]
 [0.54701793 0.36895102 0.32104767 0.36188391 0.63617151 0.56966721
  0.80477903 0.71757803]
 [0.06875733 0.96753354 0.23119232 0.82029752 0.07875969 0.92100128
  0.29691171 0.92815486]
 [0.31634368 0.71587885 0.13798137 0.20367796 0.56517152 0.12057347
  0.54587045 0.93257691]]

[[0.88296699 0.65133213 0.74443187 0.05316849 0.31516231 0.56292544
  0.59476785 0.18868536 0.06875733 0.96753354 0.23119232 0.82029752
  0.07875969 0.92100128 0.29691171 0.92815486]
 [0.54701793 0.36895102 0.32104767 0.36188391 0.63617151 0.56966721
  0.80477903 0.71757803 0.31634368 0.71587885 0.13798137 0.20367796
  0.56517152 0.12057347 0.54587045 0.93257691]]
