<a href="https://colab.research.google.com/github/ninjahurricane007/Learn.py/blob/main/TASK%2013.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
#please enter your code below this line.
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(np.sum(a))

36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [3]:
#please enter your code below this line.
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))


[ 9 12 15]
[ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [4]:
#please enter your code belowthis line.
import numpy as np
a=np.arange(0,16).reshape(4,4)
print(np.min(a))
print(np.max(a))
print(np.mean(a))


0
15
7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [21]:
#please enter your code below this line.
import numpy as np
a=np.arange(0,100).reshape(10,10)
print(a[7,:])
print()
print(a[4:9,:])
print()
print(a[5][5])
print()
print(a[ :,5])
print()
print(a[ :,2:6])


[70 71 72 73 74 75 76 77 78 79]

[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]

55

[ 5 15 25 35 45 55 65 75 85 95]

[[ 2  3  4  5]
 [12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]
 [42 43 44 45]
 [52 53 54 55]
 [62 63 64 65]
 [72 73 74 75]
 [82 83 84 85]
 [92 93 94 95]]
