<a href="https://colab.research.google.com/github/ninjahurricane007/Learn.py/blob/main/TASK%2014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [5]:
#please type your answer below this line.
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([8,18])
print(np.linalg.solve(a,b))


[2. 3.]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [7]:
#please type your answer below this line.
import numpy as np
a=np.array([2, 3, 4])
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))


[ 0.90929743  0.14112001 -0.7568025 ]

[-0.41614684 -0.9899925  -0.65364362]

[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [16]:
#please type your answer below this line.
import numpy as np
b=np.array([2, 3, 4])
a=np.sin(b)
print(2*a)
print()
c=np.cos(3*b)
print(2*c)
print()
d=np.tan(2*b)
print(4*d)

[ 1.81859485  0.28224002 -1.51360499]

[ 1.92034057 -1.82226052  1.68770792]

[  4.63128513  -1.16402477 -27.19884582]
