<a href="https://colab.research.google.com/github/ninjahurricane007/Learn.py/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [3]:
#please provide your answer below this line.
import numpy as np
print(np.random.rand(3,3))

[[0.19089337 0.17209699 0.65042646]
 [0.10525723 0.26735379 0.62418098]
 [0.40330698 0.9528592  0.60284937]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [10]:
#please provide your answer below this line.
import numpy as np
a=np.random.rand(4,4)
b=np.random.rand(4,4)
c=np.reshape(a,(2,8))
d=np.reshape(b,(2,8))
print(np.vstack(c))
print()
print(np.hstack(d))

[[0.28009562 0.57853941 0.67102665 0.15798501 0.6079399  0.85317175
  0.88195014 0.87864739]
 [0.46659799 0.86726998 0.13516781 0.9192095  0.22947075 0.01037837
  0.5022217  0.52014199]]

[0.52186003 0.17641206 0.09141566 0.50266135 0.80311668 0.30480028
 0.36753086 0.39815671 0.09168259 0.91911152 0.21250984 0.67186647
 0.18790726 0.18265987 0.11060304 0.7019024 ]
