<a href="https://colab.research.google.com/github/ninjahurricane007/Learn.py/blob/main/TASK%2010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [3]:
#please provide your answer below this line.
import numpy as np
a=np.random.rand(3,3)
b=np.random.rand(3,3)
c=np.dot(a,b)
print(c.transpose())

[[0.32180903 0.66244006 1.07449123]
 [0.24101406 0.42194242 0.72295927]
 [0.74391146 0.87423463 1.61616885]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [4]:
#please provide your answer below this line.
import numpy as np
a=np.array([[55,25,15], [30,44,2], [11,45,77]])
print(np.linalg.det(a))

137180.0000000001
